services:
  - type: web
    name: healthhelp-backend
    env: python
    buildCommand: pip install -r healthHelp/requirements.txt
    startCommand: cd healthHelp && gunicorn healthHelp.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: healthhelp-db
          property: connectionString

databases:
  - name: healthhelp-db
    databaseName: healthhelp
    user: healthhelp